spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1q2w3e4r!

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init :
      mode: always
      schema-locations: classpath:schema.sql

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

rabbitmq:
  exchange: delivery.exchange
  queue: delivery.queue
  route-key: delivery.key
